services:

  postgres:

    image: postgres:17

    container_name: dnp-postgres

    restart: unless-stopped

    environment:

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: root123

      POSTGRES_DB: postgres

    ports:

      - "5434:5432"

    volumes:

      - dnp-postgres-data:/var/lib/postgresql/data

      - ./init/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql

    healthcheck:

      test: ["CMD-SHELL", "pg_isready -U postgres"]

      interval: 10s

      timeout: 5s

      retries: 10

    networks:

      - notification-network

  redis:

    image: redis:7.2

    container_name: dnp-redis

    restart: unless-stopped

    ports:

      - "6379:6379"

    healthcheck:

      test: ["CMD", "redis-cli", "ping"]

      interval: 10s

      timeout: 5s

      retries: 5

    networks:

      - notification-network

  zookeeper:

    image: confluentinc/cp-zookeeper:7.7.0

    container_name: dnp-zookeeper

    restart: unless-stopped

    environment:

      ZOOKEEPER_CLIENT_PORT: 2181

      ZOOKEEPER_TICK_TIME: 2000

    ports:

      - "2181:2181"

    networks:

      - notification-network

  kafka:

    image: confluentinc/cp-kafka:7.7.0

    container_name: dnp-kafka

    restart: unless-stopped

    depends_on:

      - zookeeper

    ports:

      - "9092:9092"

      - "29092:29092"

    environment:

      KAFKA_BROKER_ID: 1

      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    healthcheck:

      test:
        [
          "CMD",
          "kafka-topics",
          "--bootstrap-server",
          "localhost:9092",
          "--list"
        ]

      interval: 20s

      timeout: 10s

      retries: 10

    networks:

      - notification-network

  kafka-ui:

    image: provectuslabs/kafka-ui:latest

    container_name: kafka-ui

    restart: unless-stopped

    depends_on:

      kafka:

        condition: service_healthy

    ports:

      - "8085:8080"

    environment:

      KAFKA_CLUSTERS_0_NAME: local

      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

    networks:

      - notification-network

  notification-service:

    build:

      context: ..

      dockerfile: docker/notification-service.Dockerfile

    container_name: dnp-notification-service

    env_file:

      - ../notification-service/.env

    depends_on:

      postgres:

        condition: service_healthy

      kafka:

        condition: service_healthy

      redis:

        condition: service_healthy

    ports:

      - "8080:8080"

    restart: unless-stopped

    networks:

      - notification-network

  delivery-service:

    build:

      context: ..

      dockerfile: docker/delivery-service.Dockerfile

    container_name: dnp-delivery-service

    env_file:

      - ../delivery-service/.env

    depends_on:

      postgres:

        condition: service_healthy

      kafka:

        condition: service_healthy

      redis:

        condition: service_healthy

    ports:

      - "8082:8082"

    restart: unless-stopped

    networks:

      - notification-network

volumes:

  dnp-postgres-data:

networks:

  notification-network:

    driver: bridge